name: MuscleUp Server CI-CD

on:
  push:
    branches: [ master, develop ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t ryua/muscleup:dev .

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ryua/muscleup:dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}